### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by Nyholm** [Haehnchen/idea-php-generics-plugin#3]
I found this plugin and I thought it was really cool. 

I see that it is work in progress and that there are a bunch of PHPStorm issues. Are they all blockers? Are we waiting for them to fix the issues and then the work here can continue?

**Comment by Haehnchen** [comment]
@Nyholm some reallife usages (full projects, libs) would be fine, so that i can extract the features with the most use cases first.

I also noticed some PHPStorm issues itself explicitly on DocBlock syntax parsing of custom tags, but as normal i just try to provide workaround firstly, which take its time :) i will fill some tickets for them.

**Comment by bronek89** [comment]
@Haehnchen one example of library using templates/generics is munus:
https://github.com/munusphp/munus

**Comment by simPod** [comment]
I'm doing templates here https://github.com/simPod/ClickHouseClient
